# Generated by Django 3.2.3 on 2021-08-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='completion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscribed_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
