# Generated by Django 3.2.3 on 2021-09-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210919_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='instructions',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
