# Generated by Django 3.2.3 on 2021-08-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210819_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('WD', 'Web Development'), ('CN', 'Comuter Networking')], default='CN', max_length=2),
        ),
    ]
