# Generated by Django 3.2.3 on 2021-08-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='flag',
            field=models.BooleanField(auto_created=True, default=True),
        ),
    ]
