# Generated by Django 3.2.3 on 2021-09-24 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='quiz_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='week_begin',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.week'),
        ),
    ]
