# Generated by Django 3.2.3 on 2021-09-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_flag_subscription_quiz_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='flag',
            field=models.BooleanField(auto_created=True, default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='quiz_approve',
            field=models.BooleanField(default=False),
        ),
    ]
