# Generated by Django 3.2.3 on 2021-08-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210826_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
