# Generated by Django 3.2.3 on 2021-09-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210924_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='completion',
        ),
        migrations.AddField(
            model_name='week',
            name='final',
            field=models.BooleanField(default=False),
        ),
    ]
