# Generated by Django 3.2.3 on 2021-08-27 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='week',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.week'),
        ),
    ]
