# Generated by Django 3.2.3 on 2021-09-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatecourse',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='certificatecourse',
            name='course',
        ),
        migrations.AddField(
            model_name='subscription',
            name='complete_date',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='CertificateCourse',
        ),
    ]
