# Generated by Django 3.2.3 on 2021-09-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210927_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='quiz_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='quiz_marks',
            field=models.FloatField(default=0),
        ),
    ]
