# Generated by Django 3.2.3 on 2021-09-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210927_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
    ]
